### PR TITLE
The Su-PPPOR Bowl: Optimizing Best Ball Draft Strategy via Projected …

### PR DESCRIPTION
**Pull request by zbradlow**
The Su-PPPOR Bowl: Optimizing Best Ball Draft Strategy via Projected Pick Points over Replacement 
Author: Zach Bradlow

### CODE REVIEW

**Comment by bendominguez0111** [comment]
could you add a .md or pdf file? will considered as entered @ time of PR whether its today or later

**Comment by zbradlow** [comment]
yup the PDF is knitting now, uploading a slightly old PDF version for now

**Comment by zbradlow** [comment]
how do I edit my pull request to include a .Rmd and a .pdf? new to github haha

**Comment by bendominguez0111** [comment]
just make a new commit

**Comment by zbradlow** [comment]
sounds good

**Comment by bendominguez0111** [comment]
see: https://github.com/mislav/hub/issues/198

**Comment by zbradlow** [comment]
my PDF even after using Adobe compression is 28MB and won't upload to Github, is there another way to send it?

**Comment by zbradlow** [comment]
the maximum is 25MB

**Comment by zbradlow** [comment]
let me know, I've had the PDF ready for submission

**Comment by bendominguez0111** [comment]
all good, ill upload

**Pull request merged**
